### ISSUE TITLE
Неоправданный let

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#10]
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/redux/reducer.js#L68

Нужно по-максимуму стараться избегать мутации данных (как и нечистых функций).
`Let` намекает на то, что с переменной далее что то произойдёт и нужно быть очень внимательным.

Давай избегать неоправданных `let` и там где можно, обходиться `const`.

---
Посмотри, возможно в остальном коде есть похожие проблемные места.
Отписывайся, пожалуйста, комментарием, если закончишь работу над этим issue.

**Comment by YankinaDarya** [comment]
ESLinter поправил.
