### ISSUE TITLE
Computing Derived Data

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#11]
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/redux/reducer.js#L32
Представь, что эти данные используются ещё каким-либо компонентом.
Тогда сортируя что-то в нашей таблице, возможно ты будешь изменять последовательность данных и в другом компоненте не желая того.

Вынеси сортировку в mapStateToProps или redux-hook useSelector.
\* А что бы при каждом render'е не сортировать можешь использовать useMemo (предпочтительнее для нас) или  reSelect (мы им не пользуемся).

[см. Computing Derived Data](https://redux.js.org/recipes/computing-derived-data/)

---
\* — совсем опционально
Посмотри, возможно в остальном коде есть похожие проблемные места.
Отписывайся, пожалуйста, комментарием, если закончишь работу над этим issue.

**Comment by YankinaDarya** [comment]
Я попробовала использовать createSelector, но не уверена, что все правильно сделала.
