### ISSUE TITLE
Дублирование логики в коде

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#12]
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/redux/reducer.js#L33

Здесь и ниже в REVERSED_SORT используется почти одинаковая логика сортировки.
Нужно вынести это в отдельную функцию.

**Comment by YankinaDarya** [comment]
Вынесла в отдельную стрелочную функцию Sort.

**Comment by blmzv** [comment]
Почти хорошо.
Ф-я `Sort` должна иметь 3 параметра: `profiles`, `key`, `dir`

**Comment by blmzv** [comment]
Кроме того, тут и где либо вообще нужно избегать мутации переменных и сайды-эффектов, т.к. нужно везде стремиться писать `чистые функции` (я уже писал об этом в issue «Неоправданный let»).

Видимо поэтому ты устраиваешь какую-то магию с rest- и spread-операторами:
```
const Sort = (key: string, ...profilesArray: Array<Object>): Array<Object> => {
```

```
Sort(action.key, ...state.profiles)
```

Это всё нужно убрать а в самой функции использовать следующую идею:
```
return [...profilesArray].sort(
...
)
```

**Comment by YankinaDarya** [comment]
Поправила сортировку, убрала лишние actions. В предыдущей версии я передавала копию массива, поэтому были rest и spread- операторы, но тк возвращаю все равно копию, то сейчас просто передаю сам массив.
