### ISSUE TITLE
Тут нужны константы

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#14]
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/components/Table/Table.jsx#L15

`direct` и `reversed ` нужно где-то объявить так:
```
const SORT = {
 direct: 'direct',
 reversed: 'reversed'
}
```

Что бы потом и тебе и любому другому было понятно, какие вообще есть варианты.

**Comment by YankinaDarya** [comment]
Сделала.
