### ISSUE TITLE
Убери это

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#15]
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/components/Table/Table.jsx#L23

И отпишись в комментарии, пожалуйста, как ты поняла, по какой причине (говорил на интервью).

**Comment by YankinaDarya** [comment]
Компонент реагирует на изменение props благодаря второму хуку, где указан массив зависимостей.
