### ISSUE TITLE
Главное: попробуй использовать flow

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#19]
https://flow.org

**Comment by YankinaDarya** [comment]
Попыталась использовать.

**Comment by blmzv** [comment]
`Object` — недостаточная типизация

**Comment by YankinaDarya** [comment]
Постаралась подробнее все описать.

**Comment by blmzv** [comment]
`Object` ещё кое где остался, но главное, что ты начала знакомится с типизацией. Продолжай.
