### ISSUE TITLE
Следи за форматированием кода

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#7]
Поставь ESLinter и Prettier
Это позволит следить за типичными ошибками и автоматизировать форматирование кода.

Например, тут неправильная последовательность импортов:
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/index.js#L3

---
 Отписывайся, пожалуйста, комментарием, если закончишь работу над этим issue.

**Comment by YankinaDarya** [comment]
Поставила ESLinter и Prettier, прописала несколько правил, в тч про последовательность import.
