### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by blmzv** [YankinaDarya/test-task#9]
https://github.com/YankinaDarya/test-task/blob/4368b6f20ecb30202716c8894a39173fea7fac91/src/redux/reducer.js#L59
А где обработка ошибок?

---
Посмотри, возможно в остальном коде есть похожие проблемные места.
 Отписывайся, пожалуйста, комментарием, если закончишь работу над этим issue.

**Comment by YankinaDarya** [comment]
Добавила try{} catch{}

**Comment by blmzv** [comment]
Кроме того нужно как-то обрабатывать данную ошибку на UI.
Для этого я бы предложил хранить в redux не флаг `initialized`, а `status: [STATUSES.loading, STATUSES.error, STATUSES.success]`

Попробуй, пожалуйста, если поняла идею.

**Comment by YankinaDarya** [comment]
Заменила флаг на массив возможных состояний.

**Comment by blmzv** [comment]
Почти так. ok
